In [1]:
import pandas as pd
import datetime as dt
import footballData as fd
import numpy as np
import random
import matplotlib.pyplot as plt
import datetime
import time
import Elo as ELO
import seaborn as sns

In [2]:
df1888=pd.read_csv('englandthesis.csv')
df1888

/Users/andrewpuopolo/anaconda/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2728: DtypeWarning: Columns (8) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,Unnamed: 0,Date,Season,home,visitor,FT,hgoal,vgoal,division,tier,totgoal,goaldif,result
0,1,1888-12-15,1888,Accrington F.C.,Aston Villa,1-1,1,1,1,1,2,0,D
1,2,1889-01-19,1888,Accrington F.C.,Blackburn Rovers,0-2,0,2,1,1,2,-2,A
2,3,1889-03-23,1888,Accrington F.C.,Bolton Wanderers,2-3,2,3,1,1,5,-1,A
3,4,1888-12-01,1888,Accrington F.C.,Burnley,5-1,5,1,1,1,6,4,H
4,5,1888-10-13,1888,Accrington F.C.,Derby County,6-2,6,2,1,1,8,4,H
5,6,1888-12-29,1888,Accrington F.C.,Everton,3-1,3,1,1,1,4,2,H
6,7,1889-01-26,1888,Accrington F.C.,Notts County,1-2,1,2,1,1,3,-1,A
7,8,1888-10-20,1888,Accrington F.C.,Preston North End,0-0,0,0,1,1,0,0,D
8,9,1889-04-20,1888,Accrington F.C.,Stoke City,2-0,2,0,1,1,2,2,H
9,10,1888-11-24,1888,Accrington F.C.,West Bromwich Albion,2-1,2,1,1,1,3,1,H
10,11,1888-10-06,1888,Accrington F.C.,Wolverhampton Wanderers,4-4,4,4,1,1,8,0,D
11,12,1888-10-27,1888,Aston Villa,Accrington F.C.,4-3,4,3,1,1,7,1,H
12,13,1888-10-13,1888,Aston Villa,Blackburn Rovers,6-1,6,1,1,1,7,5,H
13,14,1889-01-12,1888,Aston Villa,Bolton Wanderers,6-2,6,2,1,1,8,4,H
14,15,1888-12-22,1888,Aston Villa,Burnley,4-2,4,2,1,1,6,2,H
15,16,1888-12-29,1888,Aston Villa,Derby County,4-2,4,2,1,1,6,2,H
16,17,1888-09-22,1888,Aston Villa,Everton,2-1,2,1,1,1,3,1,H
17,18,1888-09-29,1888,Aston Villa,Notts County,9-1,9,1,1,1,10,8,H
18,19,1889-02-09,1888,Aston Villa,Preston North End,0-2,0,2,1,1,2,-2,A
19,20,1888-09-15,1888,Aston Villa,Stoke City,5-1,5,1,1,1,6,4,H
20,21,1889-01-19,1888,Aston Villa,West Bromwich Albion,2-0,2,0,1,1,2,2,H
21,22,1888-11-24,1888,Aston Villa,Wolverhampton Wanderers,2-1,2,1,1,1,3,1,H
22,23,1888-09-15,1888,Blackburn Rovers,Accrington F.C.,5-5,5,5,1,1,10,0,D
23,24,1888-11-17,1888,Blackburn Rovers,Aston Villa,5-1,5,1,1,1,6,4,H
24,25,1888-12-08,1888,Blackburn Rovers,Bolton Wanderers,4-4,4,4,1,1,8,0,D
25,26,1889-02-04,1888,Blackburn Rovers,Burnley,4-2,4,2,1,1,6,2,H
26,27,1889-04-15,1888,Blackburn Rovers,Derby County,3-0,3,0,1,1,3,3,H
27,28,1888-11-10,1888,Blackburn Rovers,Everton,3-0,3,0,1,1,3,3,H
28,29,1888-12-15,1888,Blackburn Rovers,Notts County,5-2,5,2,1,1,7,3,H
29,30,1889-01-12,1888,Blackburn Rovers,Preston North End,2-2,2,2,1,1,4,0,D
...,...,...,...,...,...,...,...,...,...,...,...,...,...
194010,194011,2017-04-22,2016,Hartlepool United,Barnet,0-2,0,2,4,4,2,-2,A
194011,194012,2017-04-22,2016,Luton Town,Notts County,2-1,2,1,4,4,3,1,H
194012,194013,2017-04-22,2016,Newport County,Accrington,1-0,1,0,4,4,1,1,H
194013,194014,2017-04-22,2016,Portsmouth,Cambridge United,2-1,2,1,4,4,3,1,H
194014,194015,2017-04-22,2016,Stevenage Borough,Mansfield Town,0-1,0,1,4,4,1,-1,A
194015,194016,2017-04-22,2016,Wycombe Wanderers,Doncaster Rovers,2-1,2,1,4,4,3,1,H
194016,194017,2017-04-29,2016,Accrington,Luton Town,1-4,1,4,4,4,5,-3,A
194017,194018,2017-04-29,2016,Barnet,Grimsby Town,3-1,3,1,4,4,4,2,H
194018,194019,2017-04-29,2016,Cambridge United,Crawley Town,2-0,2,0,4,4,2,2,H
194019,194020,2017-04-29,2016,Carlisle United,Newport County,2-1,2,1,4,4,3,1,H
194020,194021,2017-04-29,2016,Cheltenham,Hartlepool United,1-0,1,0,4,4,1,1,H
194021,194022,2017-04-29,2016,Doncaster Rovers,Exeter City,1-3,1,3,4,4,4,-2,A
194022,194023,2017-04-29,2016,Leyton Orient,Colchester United,1-3,1,3,4,4,4,-2,A
194023,194024,2017-04-29,2016,Mansfield Town,Portsmouth,0-1,0,1,4,4,1,-1,A
194024,194025,2017-04-29,2016,Morecambe,Wycombe Wanderers,1-1,1,1,4,4,2,0,D
194025,194026,2017-04-29,2016,Notts County,Blackpool,1-0,1,0,4,4,1,1,H
194026,194027,2017-04-29,2016,Plymouth Argyle,Crewe Alexandra,2-1,2,1,4,4,3,1,H
194027,194028,2017-04-29,2016,Yeovil,Stevenage Borough,1-1,1,1,4,4,2,0,D
194028,194029,2017-05-06,2016,Blackpool,Leyton Orient,3-1,3,1,4,4,4,2,H
194029,194030,2017-05-06,2016,Colchester United,Yeovil,2-0,2,0,4,4,2,2,H
194030,194031,2017-05-06,2016,Crawley Town,Mansfield Town,2-2,2,2,4,4,4,0,D
194031,194032,2017-05-06,2016,Crewe Alexandra,Barnet,4-1,4,1,4,4,5,3,H
194032,194033,2017-05-06,2016,Exeter City,Carlisle United,2-3,2,3,4,4,5,-1,A
194033,194034,2017-05-06,2016,Grimsby Town,Plymouth Argyle,1-1,1,1,4,4,2,0,D
194034,194035,2017-05-06,2016,Hartlepool United,Doncaster Rovers,2-1,2,1,4,4,3,1,H
194035,194036,2017-05-06,2016,Luton Town,Morecambe,3-1,3,1,4,4,4,2,H
194036,194037,2017-05-06,2016,Newport County,Notts County,2-1,2,1,4,4,3,1,H
194037,194038,2017-05-06,2016,Portsmouth,Cheltenham,6-1,6,1,4,4,7,5,H
194038,194039,2017-05-06,2016,Stevenage Borough,Accrington,0-3,0,3,4,4,3,-3,A
194039,194040,2017-05-06,2016,Wycombe Wanderers,Cambridge United,1-0,1,0,4,4,1,1,H

In [3]:
startdate=1958
fulldf=df1888[df1888['Season']>=startdate]
fulldf=fulldf.sort_values('Date')
fulldf=fulldf.reset_index()
fulldf=fulldf.replace('Milton Keynes Dons', 'Wimbledon')
fulldf

,index,Unnamed: 0,Date,Season,home,visitor,FT,hgoal,vgoal,division,tier,totgoal,goaldif,result
0,75629,75630,1958-08-23,1958,Swindon Town,Wrexham,1-0,1,0,3,3,1,1,H
1,75423,75424,1958-08-23,1958,Notts County,Accrington Stanley,1-1,1,1,3,3,2,0,D
2,75745,75746,1958-08-23,1958,Carlisle United,Aldershot,1-0,1,0,4,4,1,1,H
3,75743,75744,1958-08-23,1958,Bradford Park Avenue,Workington,3-2,3,2,4,4,5,1,H
4,74746,74747,1958-08-23,1958,Cardiff City,Barnsley,0-1,0,1,2,2,1,-1,A
5,75708,75709,1958-08-23,1958,Barrow,Gateshead,0-3,0,3,4,4,3,-3,A
6,74337,74338,1958-08-23,1958,Burnley,Manchester City,3-4,3,4,1,1,7,-1,A
7,74783,74784,1958-08-23,1958,Charlton Athletic,Sheffield United,1-1,1,1,2,2,2,0,D
8,74827,74828,1958-08-23,1958,Fulham,Stoke City,6-1,6,1,2,2,7,5,H
9,75637,75638,1958-08-23,1958,Tranmere Rovers,Doncaster Rovers,3-0,3,0,3,3,3,3,H
10,74313,74314,1958-08-23,1958,Bolton Wanderers,Leeds United,4-0,4,0,1,1,4,4,H
11,74857,74858,1958-08-23,1958,Huddersfield Town,Derby County,1-1,1,1,2,2,2,0,D
12,75371,75372,1958-08-23,1958,Mansfield Town,Southampton,1-6,1,6,3,3,7,-5,A
13,75601,75602,1958-08-23,1958,Stockport County,Rochdale,1-0,1,0,3,3,1,1,H
14,74896,74897,1958-08-23,1958,Leyton Orient,Bristol Rovers,1-3,1,3,2,2,4,-2,A
15,74933,74934,1958-08-23,1958,Lincoln City,Sunderland,3-1,3,1,2,2,4,2,H
16,74943,74944,1958-08-23,1958,Liverpool,Grimsby Town,3-3,3,3,2,2,6,0,D
17,74957,74958,1958-08-23,1958,Middlesbrough,Brighton & Hove Albion,9-0,9,0,2,2,9,9,H
18,75507,75508,1958-08-23,1958,Reading,Queens Park Rangers,2-2,2,2,3,3,4,0,D
19,75411,75412,1958-08-23,1958,Norwich City,Newport County,3-0,3,0,3,3,3,3,H
20,75008,75009,1958-08-23,1958,Scunthorpe United,Ipswich Town,1-1,1,1,2,2,2,0,D
21,76177,76178,1958-08-23,1958,Watford,Southport,5-1,5,1,4,4,6,4,H
22,74718,74719,1958-08-23,1958,Bristol City,Rotherham United,6-1,6,1,2,2,7,5,H
23,75344,75345,1958-08-23,1958,Hull City,Plymouth Argyle,1-1,1,1,3,3,2,0,D
24,75165,75166,1958-08-23,1958,AFC Bournemouth,Southend United,1-4,1,4,3,3,5,-3,A
25,75798,75799,1958-08-23,1958,Coventry City,Darlington,0-0,0,0,4,4,0,0,D
26,74449,74450,1958-08-23,1958,Luton Town,West Bromwich Albion,1-1,1,1,1,1,2,0,D
27,74480,74481,1958-08-23,1958,Manchester United,Chelsea,5-2,5,2,1,1,7,3,H
28,75246,75247,1958-08-23,1958,Chesterfield,Halifax Town,2-3,2,3,3,3,5,-1,A
29,75266,75267,1958-08-23,1958,Colchester United,Bury,1-3,1,3,3,3,4,-2,A
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119810,192935,192936,2017-05-07,2016,Wolverhampton Wanderers,Preston North End,1-0,1,0,2,2,1,1,H
119811,192927,192928,2017-05-07,2016,Burton Albion,Reading,2-4,2,4,2,2,6,-2,A
119812,192925,192926,2017-05-07,2016,Brentford,Blackburn Rovers,1-3,1,3,2,2,4,-2,A
119813,192357,192358,2017-05-08,2016,Chelsea,Middlesbrough,3-0,3,0,1,1,3,3,H
119814,192358,192359,2017-05-10,2016,Southampton,Arsenal,0-2,0,2,1,1,2,-2,A
119815,192360,192361,2017-05-12,2016,West Bromwich Albion,Chelsea,0-1,0,1,1,1,1,-1,A
119816,192359,192360,2017-05-12,2016,Everton,Watford,1-0,1,0,1,1,1,1,H
119817,192361,192362,2017-05-13,2016,AFC Bournemouth,Burnley,2-1,2,1,1,1,3,1,H
119818,192362,192363,2017-05-13,2016,Manchester City,Leicester City,2-1,2,1,1,1,3,1,H
119819,192363,192364,2017-05-13,2016,Middlesbrough,Southampton,1-2,1,2,1,1,3,-1,A
119820,192364,192365,2017-05-13,2016,Stoke City,Arsenal,1-4,1,4,1,1,5,-3,A
119821,192365,192366,2017-05-13,2016,Sunderland,Swansea City,0-2,0,2,1,1,2,-2,A
119822,192366,192367,2017-05-14,2016,Crystal Palace,Hull City,4-0,4,0,1,1,4,4,H
119823,192367,192368,2017-05-14,2016,Tottenham Hotspur,Manchester United,2-1,2,1,1,1,3,1,H
119824,192368,192369,2017-05-14,2016,West Ham United,Liverpool,0-4,0,4,1,1,4,-4,A
119825,192369,192370,2017-05-15,2016,Chelsea,Watford,4-3,4,3,1,1,7,1,H
119826,192370,192371,2017-05-16,2016,Arsenal,Sunderland,2-0,2,0,1,1,2,2,H
119827,192371,192372,2017-05-16,2016,Manchester City,West Bromwich Albion,3-1,3,1,1,1,4,2,H
119828,192372,192373,2017-05-17,2016,Southampton,Manchester United,0-0,0,0,1,1,0,0,D
119829,192373,192374,2017-05-18,2016,Leicester City,Tottenham Hotspur,1-6,1,6,1,1,7,-5,A
119830,192378,192379,2017-05-21,2016,Leicester City,AFC Bournemouth,1-1,1,1,1,1,2,0,D
119831,192379,192380,2017-05-21,2016,Liverpool,Middlesbrough,3-0,3,0,1,1,3,3,H
119832,192380,192381,2017-05-21,2016,Manchester United,Crystal Palace,2-0,2,0,1,1,2,2,H
119833,192381,192382,2017-05-21,2016,Southampton,Stoke City,0-1,0,1,1,1,1,-1,A
119834,192376,192377,2017-05-21,2016,Chelsea,Sunderland,5-1,5,1,1,1,6,4,H
119835,192383,192384,2017-05-21,2016,Watford,Manchester City,0-5,0,5,1,1,5,-5,A
119836,192375,192376,2017-05-21,2016,Burnley,West Ham United,1-2,1,2,1,1,3,-1,A
119837,192374,192375,2017-05-21,2016,Arsenal,Everton,3-1,3,1,1,1,4,2,H
119838,192382,192383,2017-05-21,2016,Swansea City,West Bromwich Albion,2-1,2,1,1,1,3,1,H
119839,192377,192378,2017-05-21,2016,Hull City,Tottenham Hotspur,1-7,1,7,1,1,8,-6,A

In [28]:
class Team():
    Elos=[1750,1500,1250,1000]
    def elos(x):
        return Elos[x-1]
    def __init__(self, Name, Division):
        self.team=Name
        self.league=Division
        self.ELO=elos(Division)

list

In [17]:
def elos(x):
    return Elos[x-1]
Elos=[1750,1500,1250,1000]

In [45]:
elos(3)

SyntaxError: invalid syntax (<ipython-input-45-82ae332ff283>, line 1)

In [46]:
class Rocket():
    # Rocket simulates a rocket ship for a game,
    #  or a physics simulation.
    
    def __init__(self, x=0, y=0):
        # Each rocket has an (x,y) position.
        self.x = x
        self.y = y
        
    def move_up(self):
        # Increment the y-position of the rocket.
        self.y += 1
        
# Make a series of rockets at different starting places.
rockets = []
rockets.append(Rocket())
rockets.append(Rocket(0,10))
rockets.append(Rocket(100,0))

# Show where each rocket is.
for index, rocket in enumerate(rockets):
    print("Rocket %d is at (%d, %d)." % (index, rocket.x, rocket.y))

Rocket 0 is at (0, 0).
Rocket 1 is at (0, 10).
Rocket 2 is at (100, 0).

In [47]:
class Team():
    def __init(self, Name, rating=1500, tier=1, rd=0):
        self.Name=Name
        self.rating=rating
        self.tier=tier
        self.rd=rd